services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    depends_on:
      - ganache
      - wazuh
    volumes:
      - wazuh_logs:/wazuh_logs

  ganache:
    image: trufflesuite/ganache-cli:latest
    container_name: ganache
    ports:
      - "8545:8545"

  hardhat:
    build: ./blockchain
    container_name: hardhat
    depends_on:
      - ganache

  wazuh:
    image: wazuh/wazuh-manager:4.8.2
    container_name: wazuh
    ports:
      - "1514:1514/udp"
      - "1515:1515"
    volumes:
      - wazuh_logs:/var/ossec/logs
    restart: unless-stopped

volumes:
  wazuh_logs:
